### PR TITLE
fix: correct depth-bias init/usage so blended textures depth-test correctly

### LINKED ISSUE #45: Latest changes broke texture blending
Latest changes broke texture blending. Most likely due to DX9 upgrade, not sure though.

Image

### LINKED ISSUE #47: Decals can be seen through doors
This was introduced by the d3d9 port in https://github.com/w3dhub/OpenW3D/commit/d6393fe12f31a276b6ecc9365b09d246a7430d5e

Image

### PR DESCRIPTION
**Pull request by caseychaos1212**
Fix(dx8wrapper): stabilize texture blending by correcting depth-bias init/usage
Fix(dx8renderer): Adjust DepthBias for Render_Decal_Meshes

Problems
- Depth bias was applied inconsistently, causing one textured pass to win depth
  testing and appear over another (looked like broken blending).
  
 - Depth bias for Render_Decal_Meshes was to high, causing decals to render in front of objects
 they otherwise should not be.

Changes
- Set_Default_Global_Render_States: explicitly reset depth-bias to neutral
  (D3DRS_DEPTHBIAS = 0, D3DRS_SLOPESCALEDEPTHBIAS = 0).
- Set_DX8_ZBias: use the integer ZBias for both states and apply it to slope scale:
- Set_DX8_Render_State(D3DRS_DEPTHBIAS, ZBias);
  Set_DX8_Render_State(D3DRS_SLOPESCALEDEPTHBIAS, ZBias);
  
-Updated Render_Decal_Meshes to use std::bit_cast
- Set value for DepthBias (Render_Decal_Meshes) from -0.02f to -0.001f
- Set value for SlopedScaleDepthBias (Render_Decal_Meshes) to 0.0f

Result
- Texture blending behaves as expected across passes.
- Decals no longer render in front of other geometry

Fixes #45
Fixed #47

### CODE REVIEW

File: Code/ww3d2/dx8wrapper.cpp [hunk 1]
```diff
@@ -3401,8 +3402,9 @@ void DX8Wrapper::Set_DX8_ZBias(int zbias)
 		DX8CALL(SetTransform(D3DTS_PROJECTION,(D3DMATRIX*)&tmp));
 	}
 	else {
-		float ZBias_float = zbias / 8.0f;
-		Set_DX8_Render_State (D3DRS_DEPTHBIAS, *reinterpret_cast<DWORD*>(&ZBias_float));
+		//float ZBias_float = zbias / 8.0f;
+		Set_DX8_Render_State (D3DRS_DEPTHBIAS, ZBias;
```
Comment (OmniBlade) [inline Code/ww3d2/dx8wrapper.cpp:3406]: Are you missing a closing ')' there?

**Review by OmniBlade — CHANGES_REQUESTED** [review]
Not tested yet, but this looks like a missing closing bracket?

**Review by madebr — APPROVED** [review]

**Comment by caseychaos1212** [comment]
image

image

**Review by OmniBlade — APPROVED** [review]
